name: primero
on: [push]
jobs:
  primerJob:
    runs-on: ubuntu-latest
    steps:
      - name: primerPaso
        run: echo "Hello world $GITHUB_WORKSPACE"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check file existence
        env:
          FILE: prueba/prueba.html
        shell: bash
        run: |
          if [[ -f $FILE ]]; then
            echo "$FILE exists!"
            grep 'Hola' $FILE
          else
            echo "$FILE does not exist!"
          fi
      - name: Ejecución archivo bash
        shell: bash
        env:
          RESULTADO: "paso dos"
          PRUEBA_ENV: ""
        run: | 
          ls -al hello_world.sh
          chmod +x hello_world.sh
          ./hello_world.sh
          echo $RESULTADO
      - name: Validacion paso 2
        shell: bash
        run: | 
          echo $RESULTADO 
          echo $PRUEBA_ENV
