name: primero
on: [push]
jobs:
  primerJob:
    runs-on: ubuntu-latest
    steps:
      - name: primerPaso
        run: echo "Hello world $GITHUB_WORKSPACE"
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "index.html"  
